project:
  type: book
  output-dir: _report

# quarto render
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt

execute:
  eval: true
  echo: false
  error: false
  warning: false
  message: false  # not sure if allowed
  note: false  # not sure if allowed
  freeze: auto  # during global project renders, re-render only when source changes
  
editor_options:
  chunk_output_type: console
  
editor:
  markdown:
    canonical: true  
  
format:
  html:
    number-sections: true
    toc-depth: 5
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt

book:
  title: "Model Risk Management for Pension Funds Investment Practitioners"
  subtitle: "Prepared for the Society of Actuaries"
  author: "Don Boyd and Gang Chen"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - roadmap.qmd
    - part: "Investment returns"
      chapters:
      - irfacts.qmd
      - pdist_intro.qmd
      - pdist_rnorm.qmd
      - pdist_fat_tails.qmd
      - pdist_time_corr.qmd
      - esg_intro.qmd      
    - part: "Comparing investment returns generated by different approaches"
      chapters:
      - comp_intro.qmd
    - part: "Appendix"
      chapters:
      - appdx_project_doc.qmd
      - appdx_damodaran_data.qmd
    - bibliography.qmd      
    
bibliography: _bibliography.bib
nocite: |
  @*


  

