project:
  type: book
  output-dir: _report

# quarto render
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt

execute:
  eval: true
  echo: false
  error: false
  warning: false
  message: false  # not sure if allowed
  note: false  # not sure if allowed
  freeze: auto  # during global project renders, re-render only when source changes
  
editor_options:
  chunk_output_type: console
  
editor:
  markdown:
    canonical: true  
  
format:
  html:
    number-sections: true
    toc-depth: 5
    theme: cosmo
    fig-width: 8
    fig-height: 6
  # pdf:
  #   documentclass: scrreprt

book:
  title: "Model Risk Management for Pension Funds Investment Practitioners"
  subtitle: "Prepared for the Society of Actuaries"
  author: "Don Boyd and Gang Chen"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - overview.qmd
    - questions.qmd
    - part: "Facts about investment returns"
      chapters:
      - ir_measures.qmd
      - ir_stylized_facts.qmd
      - ir_historical_facts.qmd
    - part: "Calibration of investment returns"
      chapters:
      - ir_calibration.qmd      
    - part: "Investment returns from probability distributions and similar models"
      chapters:
      - pdist_intro.qmd
      - pdist_rnorm.qmd
      - pdist_fat_tails.qmd
      - pdist_mean_reversion.qmd
    - part: "Economic scenario generators"
      chapters:      
      - esg_intro.qmd      
    - part: "Comparing investment returns generated by different approaches"
      chapters:
      - comp_intro.qmd
    - part: "Asset accumulation, as a prelude to a pension model"
      chapters:
      - accumulation_intro.qmd      
    - part: "A simple pension model"
      chapters:
      - penmod_intro.qmd  
    - part: "Impact of model structure and parameterization on key pension model outputs"
      chapters:
      - results_intro.qmd
    - part: "Appendix"
      chapters:
      - appdx_project_doc.qmd
      - appdx_damodaran_data.qmd
    - bibliography.qmd      
    
bibliography: _bibliography_web.bib
nocite: |
  @*


  

