# Parameterization and calibration cheatsheet

Parameters will change and calibration may change as the project progresses. Here is a summary of the methods used in the following analysis.

All approaches currently reflect the following:

-   50 years

-   1,000 investment returns per year

-   (50,000 observations)

-   target arithmetic mean over all observations of 7%

-   target standard deviation over all observations of 10%

+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| Approach                   | Parameterization                                                                                                                                                            | Calibration                                                                                                                            |
+============================+=============================================================================================================================================================================+========================================================================================================================================+
| Normal distribution        | no further parameters                                                                                                                                                       | linear transformation of random normal draws for x (y = a + bx)                                                                        |
+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| Fat tails (t distribution) | target excess kurtosis over 50,000 observations of 0.60, consistent with a highly positive excess kurtosis period for S&P 500 -- 30-year rolling kurtosis seen in the 2010s | -   Note: excess kurtosis of 0.60 is consistent with degrees of freedom = 14                                                           |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             | -   draw 50,000 returns from standardized t distribution with df=14                                                                    |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             | -   linear transform to mean=7%, sd=10%                                                                                                |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             | -   repeat 1,000 times (each is a simulation set)                                                                                      |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             | -   choose simulation set with excess kurtosis that has smallest squared difference from target                                        |
+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| Mean reversion             | target phi of -0.20, consistent with highly negative S&P 500 phi period - 30-year rolling phi seen in 1960-1995                                                             | -   construct a simulation set:                                                                                                        |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             |     -   draw 1,000 random normal returns for year 1, with mean=7%, sd=10%                                                              |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             |     -   for each of years 2-50, draw 1,000 random normal noise values e\[t\] with mean=0, sd=10%                                       |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             |     -   calculate return in year t: ir\[t\]=7% + -0.20\*(ir\[t-1\] - 7%) + e\[t\]                                                      |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             |     -   calculate phi (the AR(1) coefficient) for each of the 1,000 simulations                                                        |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             |     -   calculate median phi over all 1,000 simulations                                                                                |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             |     -   calculate mean and sd return                                                                                                   |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             | -   repeat for 10,000 simulation sets                                                                                                  |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             | -   calculate an error measure for each simulation set: square(mean - target mean) + square(sd - target sd) + square(phi - target phi) |
|                            |                                                                                                                                                                             |                                                                                                                                        |
|                            |                                                                                                                                                                             | -   choose simulation set, out of 10,000 sets, with smallest error                                                                     |
+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+

The result is 3 simulation sets:

-   1,000 independent normal investment returns for each of 50 years, overall mean 7%, sd 10%

-   1,000 independent t-distribution investment returns for each of 50 years, overall mean 7%, sd 10%, excess kurtosis approx 0.60

-   1,000 investment returns for each of 50 years, overall mean 7%, sd 10%; within each simulation investment returns are mean-reverting; median phi across 1,000 simulations approximately -0.20
