# More-complex multi-asset Economic Scenario Generators

We will generate investment returns from an ESG that has been used by life insurance companies and is reasonably consistent with stylized facts about investment returns. The ESG will be based upon the Academy Interest Rate Generator (AIRG) (developed by the American Academy of Actuaries and the Society of Actuaries) but we may make some modifications to make the model easier and faster to run, as we will be creating many scenario sets. The model we use will not be identified in the report as the AIRG, but rather as an ESG inspired by the AIRG.

The AIRG generates monthly interest rates at 10 points on the yield curve, monthly investment returns for four equity asset classes and monthly returns for three fixed income classes. The equity classes are U.S. diversified, international diversified, intermediate risk, and aggressive equity. The fixed-income classes are money market, intermediate Treasury, and long-term corporate bond indexes. We will collapse monthly returns to annual returns and combine returns by asset class according to target asset allocations to calculate the portfolio returns we will use in our pension model.

Returns for each equity asset class are generated by a stochastic log volatility model with 11 parameters, including long-term average volatility, the mean reversion speed for volatility, the volatility of the volatility process, the correlation between changes in volatility and changes in the underlying asset price, and the expected asset return when volatility is zero. Returns for each fixed-income class are based on the return of an appropriate maturity on the Treasury yield curve, plus 3 additional parameters relating to income and price-movement components, plus a random shock. The yield curve model estimates two points on the yield curve, each of which follows a stochastic variance model with mean reversion and has its own set of parameters (which we would not expect to change).[\[4\]](#_ftn4) It calculates other points on the yield curve by interpolation.

This model has far more parameters than we will want to modify -- with 11 parameters for each of 4 asset classes, 3 parameters for each of 3 fixed-income classes, additional parameters for the yield curve model, plus a correlation matrix of log returns and volatility, the model has more than 53 parameters. The AIRG spreadsheet model allows a user to modify only one parameter -- the mean reversion point for the long term rate in the yield curve (the rate that the 20-year Treasury yield "wants" to return to). To modify the MRP the user is required to check a box confirming that they want to override the default, which is based on NAIC guidance, with a current default of 3.25 percent.

We plan to make targeted choices about a small number of parameters to vary. To help make these choices we will speak with analysts deeply familiar with the AIRG and with stochastic log volatility models more generally, review relevant research, and review carefully the AIRG model code.