# Project document

This section is the project document we agreed to in February 2023, with minor nonsubstantive edits. For the original pdf, click [here](https://drive.google.com/file/d/1iAtAQtC2Yn1l8U4jAOOuDGeIAET0K8_g/view?usp=sharing).

<font size="6">**Model Risk Management for Pension Funds Investment Practitioners**</font>

Updated description of Project and Report

Don Boyd and Gang Chen, Rockefeller College

February 13, 2023


### Goal and approach

The goal is to prepare a report that will help pension fund practitioners understand the risks associated with models used for pension fund investment and funding decision-making. The report will focus primarily on risks related to stochastic economic scenario generators (ESGs) used as inputs to pension investment and funding models.

The key question the report will address is, to what extent might choices about the structure or parameters of an ESG model lead to meaningful alternative conclusions about pension-related risks?

For example, would choosing an ESG model with structure A lead to materially different conclusions about pension risks than if a model with structure B had been chosen? Would choosing parameters **X** for model A lead to materially different conclusions about pension risks than if parameters **Y** had been chosen for model A? An example of a risk of potential interest is the risk of severe pension underfunding in some time period.

The ultimate question of interest is to what extent might different choices about model structure and parameterization lead to different *decisions* of interest such as asset allocation? Our analysis will shed light on investment decisions but it will not be goal-seeking -- for example, it will not seek asset allocations that optimize goals of pension fund managers such as minimizing a particular risk measure.[\[1\]](#_ftn1) However, it will be practical to run selected combinations of structure and parameterizations under a small set of alternative asset allocations to provide insight into how asset allocation choice might be affected. This would be a targeted exercise, using a small number of asset allocation options.

The report will examine the key question using simple ESG models that produce inputs for a simple pension model, allowing analysis of resulting model conclusions about pension risks.

Among other things, the report will provide advice to pension fund practitioners on questions to ask about the ESG and pension models they use to evaluate pension risks.

### ESG models

We suggest three approaches to evaluating how alternative ESG structures and parameters alter perceived pension risks. We will definitely use the first and third approaches below, and also the second approach if that is of interest to SOA. For the third approach (multi-asset approaches), we will construct annual portfolio returns from asset-class returns assuming annual rebalancing to achieve target allocations.

#### **#1: Portfolio returns generated by simple probability distributions**

While these distributions will not fit real-world investment return data well, and will not reproduce stylized facts about investment returns, they can allow isolation of important variables, thereby producing useful insights; they can also serve as baselines for comparison:

-   **Simple time-independent random normal distribution portfolio-returns**, parameterized with mean and standard deviation. This will be useful for generating baseline pension-risk results, against which risks from other scenario generators can be compared.

-   **A probability distribution that can generate time-independent fat-tailed returns**, such as the Student's t distribution, parameterized by mean, standard deviation, and degrees of freedom.

-   **A multivariate normal distribution with returns correlated over time**, parameterized by mean, standard deviation, and a correlation matrix.

#### **#2: A simple two-asset stocks-bond model** (if of interest)

Returns would be generated from a multivariate probability distribution or a simple stochastic process such as multivariate geometric Brownian motion, parameterized by mean, standard deviation, and correlation of two asset classes. As with the simple probability distributions, this would not be expected to be consistent with stylized facts about investment returns.

#### **#3: A more-complex multi-asset ESG**

We will generate investment returns from an ESG that has been used by life insurance companies and is reasonably consistent with stylized facts about investment returns. The ESG will be based upon the Academy Interest Rate Generator (AIRG) (developed by the American Academy of Actuaries and the Society of Actuaries) but we may make some modifications to make the model easier and faster to run, as we will be creating many scenario sets. The model we use will not be identified in the report as the AIRG, but rather as an ESG inspired by the AIRG.

The AIRG generates monthly interest rates at 10 points on the yield curve, monthly investment returns for four equity asset classes and monthly returns for three fixed income classes.[\[2\]](#_ftn2) The equity classes are U.S. diversified, international diversified, intermediate risk, and aggressive equity. The fixed-income classes are money market, intermediate Treasury, and long-term corporate bond indexes.[\[3\]](#_ftn3) We will collapse monthly returns to annual returns and combine returns by asset class according to target asset allocations to calculate the portfolio returns we will use in our pension model.

Returns for each equity asset class are generated by a stochastic log volatility model with 11 parameters, including long-term average volatility, the mean reversion speed for volatility, the volatility of the volatility process, the correlation between changes in volatility and changes in the underlying asset price, and the expected asset return when volatility is zero. Returns for each fixed-income class are based on the return of an appropriate maturity on the Treasury yield curve, plus 3 additional parameters relating to income and price-movement components, plus a random shock. The yield curve model estimates two points on the yield curve, each of which follows a stochastic variance model with mean reversion and has its own set of parameters (which we would not expect to change).[\[4\]](#_ftn4) It calculates other points on the yield curve by interpolation.

This model has far more parameters than we will want to modify -- with 11 parameters for each of 4 asset classes, 3 parameters for each of 3 fixed-income classes, additional parameters for the yield curve model, plus a correlation matrix of log returns and volatility, the model has more than 53 parameters. The AIRG spreadsheet model allows a user to modify only one parameter -- the mean reversion point for the long term rate in the yield curve (the rate that the 20-year Treasury yield "wants" to return to). To modify the MRP the user is required to check a box confirming that they want to override the default, which is based on NAIC guidance, with a current default of 3.25 percent.

We plan to make targeted choices about a small number of parameters to vary. To help make these choices we will speak with analysts deeply familiar with the AIRG and with stochastic log volatility models more generally, review relevant research, and review carefully the AIRG model code.

The three-pronged approach will allow three categories of model structures -- simple probability distributions, two-asset models, and AIRG-based returns. In addition, it could allow alternative model structures within a category -- for example, different probability distributions can be used within the probability distribution structure, as discussed above.

And the approach allows different parameterizations within any model structure by varying the parameters describe above.

There will not always be a clear distinction between model structure and model parameterization. As a trivial example, as the number of degrees of freedom in the Student's t-distribution becomes large, the t-distribution approaches the normal distribution and will not have fat tails. So a change in parameters of the t distribution can effectively change the model from a fat-tailed model to a normal distribution model. Similarly, setting the mean reversion parameters in an AIRG-type model to zero in a sense changes the character of the model.

It's important to make meaningful comparisons across models and parameterizations. In general, we expect to make comparisons of risk measures across scenario sets that have approximately the same expected return, and possibly similar standard deviations, calculated over a long period of time (e.g., 50 years). We may not be able to make all models comparable in this way; to the extent we cannot, we expect to use time-independent normal returns as a common baseline for comparison (for example, how do risk measures based on scenario set A compare to those based on a random normal set that matches its mean and standard deviation, and how do risk measures based on scenario set B compare to a random normal set that matches its mean and standard deviation?)

We will examine and compare characteristics of investment return scenario sets produced by different ESG models and parameterizations in several ways, including empirical moments and variation over time. We will include selected results in the report appendix and will discuss scenario set comparisons with SOA and the POG during the project.

### Pension model

We plan to construct a simple defined benefit pension model with no demographic component and a simple funding rule, with the following characteristics:

-   A closed plan with a fixed lifetime such as 100 years

-   Pension benefit payouts grow at a constant rate which could be zero or based on other factors such as the inflation rate

-   Liability in any year is the present value of remaining future benefits at either:

    -   a fixed assumed discount rate, or

    -   a market-related discount rate.

    -   The latter raises a question of what discount rate to use for the probability-distribution models - #1 above - that do not have associated market interest rates.

-   Initial assets would be set to initial liability. It would be possible to allow initial underfunding and add a fixed contribution rule that amortizes initial underfunding over the plan lifetime. We would propose not updating contributions based on plan funded status.

-   A single simulation (one instance within a scenario set) would walk this plan year by year through its lifetime, calculating investment income based on a stochastic investment return, and calculating ending assets as starting assets plus investment income plus any contributions, minus benefit payouts. Remaining liability would be calculated as the present value of remaining benefit payments at the year in question, valued at either the fixed discount rate or market-related discount rate.

-   This would allow calculation in any simulation, in any year, of the plan's funded status.

-   For any given model structure and parameterization, we would run many simulations (e.g., 10,000). This would allow us to examine the distribution of risks of underfunding, and how they vary over time, and how they vary with model structure and parameterization.

This seems like it might have sufficient flexibility and details for the purpose at hand.[\[5\]](#_ftn5) One extension of interest could be to incorporate a funding rule that amortizes newly occurring unfunded liabilities very simply, such as a level-dollar rolling 20-year amortization period, but that raises complications, for example, about what to do when the plan becomes overfunded and whether to allow negative contributions, so we'd propose not having new contributions, allowing us to keep things simple.

### Other project components

The project report will describe pension model risks in general and what is known from research, but these sections will be brief. In addition, it will explore briefly what is known about evaluation of model structure and parameter risks based on documents exposed in the ongoing NAIC/Conning model development and testing process.

The centerpiece of the report will be risk-analysis based on scenario sets from different ESG models described above, and different parameterizations of those models. The goal will be to understand the extent to which model-structure choice and parameterizations affect decision-relevant variables of interest to pension practitioners. The ultimate interest is to gain insight into how model choice and parameterization might affect decisions such as asset allocation, but what we will quantify are implications for decision-relevant variables (such as risks related to pension plan funding status or solvency).

The report will end with advice to pension fund practitioners on questions to ask about the ESG and pension models they use to evaluate pension risks.

### Report outline

 

-   Executive summary

-   Introduction

    -   Project goals

    -   Project approach

-   Pension plan risks

    -   Important pension plan risks

    -   Which risks are most important, based on what we know from research/industry analysis? (investment return risks are paramount)

-   Pension model risks (focusing on ESGs)

    -   How plan risks are reflected in models

    -   Risks in ESG models -- this discussion will draw on several excellent sources, including AIRG documentation, documents related to validation and testing in the NAIC/Conning modeling, and several other documents that we have exchanged or discussed via email

        -   Model goals

        -   Model choice

        -   Model parameters

-   Testing the importance of model choice and parameterization

    -   This section will have our analysis of model structure and parameterization risks, as discussed above.

-   Summary and conclusions

    -   What are the biggest pension risks?

    -   How important are choice of model-structure and model parameterization to *estimated* risks of concern to pension fund practitioners? (The risks don't change when model structure or parameterization change, but the estimates of those risks will change. So the question here is, to what extent do these choices alter estimates and conclusions about risks.

    -   What insights can we glean about importance of model-structure choice and parameterization to decisions that pension fund management must make?

-   Advice for practitioners

    -   What do practitioners need to know about pension funding models that they are considering using?

    -   What questions should they ask?

        -   References

        -   Appendix

------------------------------------------------------------------------

[\[1\]](#_ftnref1) Asset-allocation goal-seeking would require many runs of each model-structure choice and parameterization combination, each with different asset allocations, which we do not consider practical in this project.

[\[2\]](#_ftnref2) This discussion is based on our analysis of the spreadsheet model and the model description in "C3 Phase II Risk-Based Capital for Variable Annuities: Pre-Packaged Scenarios:  Presented by the American Academy of Actuaries' Life Capital Adequacy Subcommittees' C-3 Phase 2 Work Group to the National Association of Insurance Commissioners' Capital Adequacy Task Force" (American Academy of Actuaries, March 2005), https://www.actuary.org/sites/default/files/pdf/life/c3supp_march05.pdf. We have verified that the latest spreadsheet model (Version 7.1.2205) Visual Basic code is consistent with this documentation in all important respects.

[\[3\]](#_ftnref3) The specific market indexes used as proxies for each asset class are given in documentation just cited.

[\[4\]](#_ftnref4) See "C3_Phase_I\_Report_October_1999.Pdf \-- Interest Rate Documentation," accessed January 8, 2023, https://www.actuary.org/sites/default/files/files/C3_Phase_I\_Report_October_1999.pdf. We have verified that the latest spreadsheet model (Version 7.1.2205) is consistent with this documentation.

[\[5\]](#_ftnref5) We do not propose incorporating a funding rule that amortizes newly occurring unfunded liabilities very simply, such as a level-dollar rolling 20-year amortization period. This would raise complications not necessary for the issue at hand \-- for example, about what to do when the plan becomes overfunded and whether to allow negative contributions.
